deployment:
  replicaCount: 1
  purllPolicy: IfNotPresent
  repository: "sladuca/codemems"
  tag: "scheduler"
  name: "scheduler"

service:
  clusterPort: 8000
  podPort: 8000
  NodePort: 30003
  name: "scheduler-service"
