# the note registry itself
apiVersion: extensions/v1beta1
kind: {{ .Values.deployment.name }}
metadata:
  name: {{ .Values.deployment.name }}
spec: 
  containers:
    # docker container to use
    - name: data-pipeline
      image: "{{ .Values.repository }}:{{ .Values.tag }}"
      imagePullPolicy: {{ .Values.pullPolicy }}
      ports:
        - name: http
          # port of the container to expose to incoming http
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
        # environment variabels to set within the container upon startup
      env:
        - name: RABBIT_HOSTNAME
          value: "{{ .Release.Name }}-{{ .Values.rabbitHost }}"
        - name: MONGO_HOST
          value: {{ .Values.mongo.ip }}
        - name: MONGO_PORT
          value: {{ .Values.mongo.port }}
