# exposes the pods that make up the jawn as a service for other services
# in the cluster to be able to access
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: "codemems"
    component: {{ .Values.service.name }}
    environment: {{ .Values.deployment.env }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.clusterPort }} # port accessible from within the cluster
      name: {{ .Values.service.name }}
      target-port: {{ .Values.service.podPort }} # port accessible from within a pod
      NodePort: {{ .Values.service.ExternalPort }} # port accessible from outside the cluster
      protocol: TCP
  selector:
    app: "codemems"
    component: {{ .Values.service.name }}
    environment: {{ .Values.deployment.env }}
