dependencies:
  - name: nginx-ingress
    repository: "@stable"
    version: 1.17.1
  - name: rabbitmq
    repository: "@stable"
    version: 6.4.2
  - name: mongodb
    repository: "@stable"
    version: 7.2.7
    import-values:
      - child: service
        parent: mongoService
  - name: card-registry
    repository: "@local"
    version: 0.1.0
    import-values:
      - child: service
        parent: cardService
  - name: note-registry
    repository: "@local" 
    version: 0.1.0
    import-values:
      - child: service
        parent: noteService
  - name: data-pipeline
    repository: "@local"
    version: 0.0.1
    import-values:
      - child: service
        parent: dataService
  - name: scheduler
    repository: "@local"
    version: 0.0.1
    import-values:
      - child: service
        parent: schedulerService
  - name: frontend
    repository: "@local"
    version: 0.0.1
    import-values:
      - child: service
        parent: frontendService
