dependencies:
  - name: nginx-ingress
    repository: "@stable"
    version: 1.17.1
  - name: rabbitmq
    repository: "@stable"
    version: 6.4.2
  - name: mongodb-replicaset
    repository: "@stable"
    version: 3.9.6
  - name: card-registry
    repository: "@local"
    version: 0.1.0
  - name: note-registry
    repository: "@local" 
    version: 0.1.0
  - name: data-pipeline
    repository: "@local"
    version: 0.1.0
  - name: scheduler
    repository: "@local"
    version: 0.1.0
  - name: frontend
    repository: "@local"
    version: 0.1.0
