dependencies:
  - name: nginx-ingress
    repository: "@stable"
    version: ~1.24.0
    alias: nginxIngress
  - name: rabbitmq
    repository: "@stable"
    version: ~6.8.2
  - name: mongodb-replicaset
    repository: "@stable"
    version: ~3.10.1
    alias: mongo
  - name: card-registry
    repository: "@local"
    version: 0.1.0
    alias: cardRegistry
  - name: note-registry
    repository: "@local" 
    version: 0.1.0
    alias: noteRegistry
  - name: data-pipeline
    repository: "@local"
    version: 0.1.0
    alias: dataPipeline
  - name: scheduler
    repository: "@local"
    version: 0.1.0
  - name: frontend
    repository: "@local"
    version: 0.1.0
