# Default values for codemems.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
pullPolicy: IfNotPresent

card-registry:
  repository: "sladuca/codemems"
  tag: card-registry

note-registry:
  repository: "sladuca/codemems"
  tag: note-registry
  
