deployment:
  replicaCount: 1
  pullPolicy: IfNotPresent
  repository: "sladuca/codemems"
  tag: "card_registry"
  name: "card-registry"
  env: "dev"

service:
  clusterPort: 8000
  podPort: 8000
  containerPort: 8000
  NodePort: 30000
  name: "card-registry-service"
  
rabbit:
  host: "rabbitmq.default.svc.cluster.local"

mongo:
  host: nil
  port: 27017
