replicaCount: 1
pullPolicy: IfNotPresent

serviceName: "card-registry-service"
deploymentName: "card-registry"
env: "dev"

repository: "sladuca/codemems"
tag: "card_registry"

clusterPort: 8000
podPort: 8000
containerPort: 8000
NodePort: 30000

rabbitHost: "rabbitmq.default.svc.cluster.local"
