# exposes the pods that make up card registry as a service for other services
# in the cluster to be able to access
apiVersion: v1
kind: Service
metadata:
  name: cardRegistryService
spec:
  type: NodePort
  ports:
    - port: {{ .Values.clusterPort }} # port accessible from within the cluster
      name: cardRegistryService
      target-port: {{ .Values.podPort }} # port accessible from within a pod
      NodePort: {{ .Values.ExternalPort }} # port accessible from outside the cluster
      protocol: TCP
---
# the note registry itself
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cardRegistry
spec:
  containers:
    # docker image to use 
    - name: card-registry
      image: "{{ .Values.repository }}:{{ .Values.tag }}"
      imagePullPolicy: {{ .Values.pullPolicy }}
      ports:
        - name: http
          # port of the container to expose to incoming http
          containerPort: 80
          protocol: TCP
        # environment variables to set within the container upon startup
        env:
          - name: RABBIT_HOSTNAME
            value: "{{ .Release.Name }}-rabbitmq.default.svc.cluster.local"

